/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 globe3d.glb 
Author: spaceexpert (https://sketchfab.com/spaceexpert)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-globe-sci-fi-look-8434c67a411f484c81db412b49de0427
Title: Earth Globe Sci-Fi Look
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/globe3d.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2, 0.059, -Math.PI]} scale={0.022}>
          <group name="globe_uiFBX" rotation={[-Math.PI, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="graph" rotation={[Math.PI / 2, 0, 0]}>
                  <mesh name="graph_graph_0" geometry={nodes.graph_graph_0.geometry} material={materials.graph} />
                </group>
                <group name="DOTS">
                  <mesh name="DOTS_dots_0" geometry={nodes.DOTS_dots_0.geometry} material={materials.dots} />
                </group>
                <group name="graph_02" rotation={[Math.PI / 2, -Math.PI / 3, 0.96]}>
                  <mesh name="graph_02_graph_0" geometry={nodes.graph_02_graph_0.geometry} material={materials.graph} />
                </group>
                <group name="Dummy001" rotation={[Math.PI / 2, 0, 0.41]}>
                  <group name="globe_ambient" rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh name="globe_ambient_globe_ambient_0" geometry={nodes.globe_ambient_globe_ambient_0.geometry} material={materials.globe_ambient} />
                  </group>
                  <group name="main_globe" rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh name="main_globe_main_0" geometry={nodes.main_globe_main_0.geometry} material={materials.main} />
                  </group>
                  <group name="clouds" rotation={[-Math.PI / 2, -0.428, 0]}>
                    <mesh name="clouds_clouds_0" geometry={nodes.clouds_clouds_0.geometry} material={materials.clouds} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/globe3d.glb')
